name: wsj_tweet_scrapping
channels:
  - conda-forge
dependencies:
  - ipykernel
  - openpyxl
  - nltk
  - nodejs
  - pip
  - python
  - tqdm
  - pip:
      - glob3
      - pickle-mixin
      - nest_asyncio
      - lxml
      - xlrd
      - urllib3
      - beautifulsoup4
      - spacy
