name: wsj_tweet_scrapping
channels:
  - conda-forge
dependencies:
  - black
  - flake8
  - ipykernel
  - isort
  - jupyterlab
  - openpyxl
  - nltk
  - nodejs
  - pip
  - python
  - pycodestyle
  - pydocstyle
  - selenium
  - tqdm
  - pip:
      - pickle-mixin
      - nltk
      - lxml
      - xlrd
      - urllib3
      - beautifulsoup4
      - spacy
